name: kr_expanded_section
description: A Flutter package to create an expandable section in your app.
version: 1.0.0
homepage: https://github.com/karrarfalih/kr_expanded_section

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

